name: release

on:
 pull_request:
 push:
  branches: [ main ]

jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    # Run the steps below with the following versions of Node.js
    node-version: [14.17.x]
  steps:
  # Fetch the latest commit
  - name: Checkout
   uses: actions/checkout@v2

  # Setup Node.js using the appropriate version
  - name: Use Node.js ${{ matrix.node-version }}
   uses: actions/setup-node@v1
   with:
    node-version: ${{ matrix.node-version }}

  # Install package dependencies
  - name: Install
   run: npm ci

 release:
  # Only release on push to master
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  # Waits for test jobs for each Node.js version to complete
  steps:
  - name: Checkout
   uses: actions/checkout@v2

  - name: Setup Node.js
   uses: actions/setup-node@v1
   with:
    node-version: 12.x

  - name: Install
   run: npm ci

  - name: Release
   run: npx semantic-release
   env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}